### ISSUE TITLE
searchPaths vs. gulp.src

### ISSUE THREAD

**Issue by heyallan** [gianlucamancini/gulp-nunjucks-html#5]
Can you help me understand the difference between `searchPaths` and `gulp.src`.

I know one is the the source files and the other one is "the path for where templates live", but why do I need this path when I'm already passing `gulp.src`? I don't get the difference.

Thanks.

**Comment by gianlucamancini** [comment]
The goal of `gulp.src` is to find all files that match a given expression: it gives the Nunjucks compiler (this plugin) information like the file path and its contents. However, in order to make things like relative extends (`{% extends "base.html" %}`) you have to tell the compiler the root directory (or more) to look for these files.

**Comment by heyallan** [comment]
So one represent the files, and the other just the relative paths?

**Comment by gianlucamancini** [comment]
Yes.

**Comment by heyallan** [comment]
Kudos! Thank you very much :+1:
